<?php include_once "db_connection.php";

function FormatCopyPasta($status_desc, $signed_by, $char_name, $additionalInfo)
{
    include_once "db_connection.php";
    echo "Hello " . $char_name . ".<br>";
    echo "Unfortunately, your application for Downtown Cab Co. has been Rejected.<br>";
    echo "The reason(s) given are as follows:<br><br>";
    $reasons = explode("/", $status_desc);
    if ($reasons[0] == 1) {
        echo "You have been barred from using DTCC Services.<br><br>";
    }
    if ($reasons[1] == 1) {
        echo "Your Character Name is invalid.<br>";
    }
    if ($reasons[2]) {
        echo "Your Phone Number is invalid.<br>";
    }
    if ($reasons[3]) {
        echo "Your Discord Username is incorrect.<br>";
    }
    if ($reasons[4]) {
        echo "We cannot find your SteamID from the provided URL. (Do you have your profile set to private?)<br>";
    }
    if ($reasons[5]) {
        echo "Your Backstory is invalid.<br>";
    }
    if ($reasons[6]) {
        echo "Your reason for wanting to join us is invalid.<br>";
    }
    if ($additionalInfo) {
        echo "<br>Additional Info:<br>";
        echo $additionalInfo . "<br><br>";
    }
    if ($reasons[7]) {
        if ($reasons[8] == 0) {
            echo "We recommend you create another application as soon as you can.<br>";
        }
        if ($reasons[8] == 1) {
            echo "We recommend that you reapply tomorrow.<br>";
        }
        if ($reasons[8] > 1) {
            echo "We recommend that you reapply in " . $reasons[8] . " days.<br>";
        }
    }
    if (!$reasons[7]) {
        echo "We recommend that you do not apply for DTCC again.<br>";
    }

    echo "Regards<br>" . q_fetchPlayerFormatted($signed_by) . "<br> (This message was autogenerated.)";
}

function FormatReasons($status_desc, $additionalInfo)
{
    $reasons = explode("/", $status_desc);
    if ($reasons[0] == 1) {
        echo "<li>User was previously Banned from DTCC.</li>";
    }
    if ($reasons[1] == 1) {
        echo "<li>Invalid Character Name</li>";
    }
    if ($reasons[2]) {
        echo "<li>Invalid Phone Number</li>";
    }
    if ($reasons[3]) {
        echo "<li>Invalid Discord Name</li>";
    }
    if ($reasons[4]) {
        echo "<li>Invalid Steam Profile Link</li>";
    }
    if ($reasons[5]) {
        echo "<li>User's backstory is improper.</li>";
    }
    if ($reasons[6]) {
        echo "<li>User's reason is improper.</li>";
    }
    if ($reasons[7]) {
        if ($reasons[8] == 0) {
            echo "They have been asked to reapply immediately.<br>";
        }
        if ($reasons[8] == 1) {
            echo "They have been asked to reapply tomorrow.<br>";
        }
        if ($reasons[8] > 1) {
            echo "They have been asked to reapply in " . $reasons[8] . " days.<br>";
        }
    }
    if (!$reasons[7]) {
        echo "They have been asked not to reapply again<br>";
    }
    if ($additionalInfo) {
        echo "Additional Info: <br><br>";
        echo $additionalInfo . "<br>";
    }
}
?>

<div class="row">
    <div class="col">
        <h6 class="mb-3">
            <?php echo "<p class='text-danger'>This application was Denied by " . q_fetchPlayerFormatted($signed_by) . " for the following reasons:</p>" ?>
        </h6>
        <?php FormatReasons($status_desc, $additionalInfo); ?>
    </div>
    <div class="col">
        <h6>Below is a Copy/Paste to send directly to them:</h6>
        <div class="border text-left">
            <?php FormatCopyPasta($status_desc, $signed_by, $char_name, $additionalInfo); ?>
        </div>
    </div>
</div>